---
title: "Dolphin_Vocal_Sighting_Analyses_Final_Bimonthly"
output: html_document
---

```{r}
library(scales)
library(MASS)
library(ggplot2)
require(gridExtra)
library(ggpubr)
library(car)
library(RColorBrewer)
library(DTK)
library(lmtest)
```

```{r}
#data import
dolphinz <- read.csv("~/Desktop/Sighting Data/bimonthly.csv")
#specify categorical factors
dolphinz$site <- factor(dolphinz$site)
dolphinz$season <- factor(dolphinz$season)
dolphinz$season <- factor(dolphinz$season, levels = c("Winter", "Spring", "Summer", "Fall"))
dolphinz$site <- factor(dolphinz$site, levels = c("Citadel","Ashley River","Ft Sumter","SC Aquarium", "Drum Island","Wando River"))

#subset data to look at histograms of vocalization and sightiing frequency across survey areas
stna <-  subset(dolphinz, site=="Wando River")
stnc <- subset(dolphinz, site=="SC Aquarium")
stnb <-  subset(dolphinz, site=="Drum Island")
stnd <-  subset(dolphinz, site=="Ft Sumter")
stne <- subset(dolphinz, site=="Ashley River")
stnf <-  subset(dolphinz, site=="Citadel")
```

```{r}
#overall histograms showing vocalization and sighting frequency respectively
par(mfrow=c(1,2))
hist(dolphinz$total,  xlab = "Total Number of Vocalizations", breaks = 8, main = "Vocalization Frequency")
hist(dolphinz$dolphin,  xlab = "Total Number of Dolphins", main = "Sighting Frequency") 
```

```{r}
#histograms for vocalizations and dolphins sighted at stations A, B, and C
par(mfrow=c(2,3))
hist(stna$total,  xlab = "Total Number of Vocalizations", main = "Wando River") 
hist(stnb$total,  xlab = "Total Number of Vocalizations", main = "Drum Island") 
hist(stnc$total,  xlab = "Total Number of Vocalizations", main = "SC Aquarium") 
hist(stna$dolphin,  xlab = "Total Number of Dolphins", main = "Wando River") 
hist(stnb$dolphin,  xlab = "Total Number of Dolphins", main = "Drum Island") 
hist(stnc$dolphin,  xlab = "Total Number of Dolphins", main = "SC Aquarium") 
```
```{r}
#histograms for vocalizations and dolphins sighted at stations D, E, and F
par(mfrow=c(2,3))
hist(stnd$total,  xlab = "Total Number of Vocalizations", main = "Ft Sumter") 
hist(stne$total,  xlab = "Total Number of Vocalizations", main = "Ashley River") 
hist(stnf$total,  xlab = "Total Number of Vocalizations", main = "Citadel") 
hist(stnd$dolphin,  xlab = "Total Number of Dolphins", main = "Ft Sumter") 
hist(stne$dolphin,  xlab = "Total Number of Dolphins", main = "Ashley River") 
hist(stnf$dolphin,  xlab = "Total Number of Dolphins", main = "Citadel") 
```

Model Testing -

```{r}
#First basic regression not including other environmental, temporal, and spatial factors 
#R squared value is very low, likely due to not including the other factors likely at play explaining the relationship

#Multiple regression including all factors I want to assess -- overfitting the data, move forward with glm and then tukeys hsd mult comparisons for factors and pearson correlations for continuous variables that are significant. 

#Multiple llinear regression was first attempted but due to the large number of factors included moved forward
#with general linear modeling. Tested multiple models (Poisson, Negative Binomial, Gaussian with no transforms,
# and Gaussian with transformations) and compared using AIC criteria, landing on a model with log+1 transformations of total vocalizations and total dolphins sighted.

#First tested the possible effect of calf presence by separating total dolphin count into adult and calf
#Found no significant effect and the model shows significantly lower AIC and in testing model with AIC 
#the model was better if calf was dropped (AIC lower than 2 points) 

#basictot_lm <- lm(log1p(total) ~ dolphin, data = dolphinz)
#summary(basictot_lm)
#plot(basictot_lm)
#R squared ~ 0.2


#TOTAL VOCALIZATIONS
logtotal.glm <- glm(log1p(total) ~ dolphin + site + season + drum + perch, data = dolphinz)
summary(logtotal.glm)
plot(logtotal.glm)
stepAIC(logtotal.glm)
#remove noise ratio, toad, trout
#without log+1(total) AIC = 1033.9
#with log+1(dolphin) AIC = 349.7
```

```{r}
#Can see degrees of freedom, sum of squares, and p-values for each variable against total vocals
alog.glm <- aov(logtotal.glm)
summary(alog.glm)
```
```{r}
#Testing Negative Binomial and Poisson GLM distributions
total.glmnb <- glm.nb(total ~ dolphin + site + season + perch, data = dolphinz)
summary(total.glmnb)
plot(total.glmnb)
#AIC 678.03

total.glmpois <- glm(total ~ dolphin + site + season + perch, family = poisson, data = dolphinz)
summary(total.glmpois)
plot(total.glmpois)
#AIC 2033

#Gaussian GLM with Log+1 transformation of total vocalizations best model fit - AIC 346.61
```

```{r}
#Followed up with a likelihood ratio test to compare the effects of each factor - TOTAL VOCALS

logtotal.glm <- glm(log1p(total) ~ dolphin + site + season + perch + drum, data = dolphinz)
logtotal.glm2 <- glm(log1p(total) ~ site + season + perch +  drum, data = dolphinz)
logtotal.glm3 <- glm(log1p(total) ~ dolphin + season + perch + drum, data = dolphinz)
logtotal.glm4 <- glm(log1p(total) ~ dolphin + site + perch + drum, data = dolphinz)
logtotal.glm5 <- glm(log1p(total) ~ dolphin + site + season + drum, data = dolphinz)
logtotal.glm6 <- glm(log1p(total) ~ dolphin + site + season + perch, data = dolphinz)

lrtest(logtotal.glm, logtotal.glm2) #dolphin
lrtest(logtotal.glm, logtotal.glm3) #site
lrtest(logtotal.glm, logtotal.glm4) #season
lrtest(logtotal.glm, logtotal.glm5) #perch
lrtest(logtotal.glm, logtotal.glm6) #drum
```

```{r}
#Tukeys HSD multiple comparisons for site and season effects/importance --                              How do I report these results? & If in graphs, how do I get the y labels to show?

TK.total <- TK.test(dolphinz$total, dolphinz$site, a=0.05)
TK.total
plot(TK.total)
TK.dolpht <- TK.test(dolphinz$dolphin, dolphinz$site, a=0.05)
TK.dolpht
plot(TK.dolpht)

TK.totszn <- TK.test(dolphinz$total, dolphinz$season, a=0.05)
TK.totszn
plot(TK.totszn)
TK.dolphszn <- TK.test(dolphinz$dolphin, dolphinz$season, a=0.05)
TK.dolphszn
plot(TK.dolphszn)
```

```{r}
#Pearson Correlations to further assess relationships with continuous variables - Dolphins sighted

# total vocals ~ dolphin count
ggscatter(dolphinz, x = "dolphin", y = "total",
          add = "reg.line",                         
          conf.int = TRUE ,      
 xlab = "Total Dolphins Sighted", ylab = "Log+1(Total Vocalizations Detected)")+
  stat_cor(aes(x=dolphin, y=log1p(total)), label.x = 20)

#Testing Assumptions of Pearson's Correlation

ggqqplot(dolphinz$dolphin, ylab = "Total Dolphins Sighted")
# wt
ggqqplot(log1p(dolphinz$total), ylab = "Log+1(Total Vocalizations Detected)")
restot.1 <- cor.test(dolphinz$dolphin, log1p(dolphinz$total), 
                    method = "pearson")
restot.1
#looks good
```

```{r}
#Plots to further assess the fit of my model, on the left predicted values based on the model compared to observed and on the right the residuals plotted against the fitted values to make sure there is no pattern
par(mfrow=c(1,2))

plot(predict(logtotal.glm), log1p(dolphinz$total), xlab='Predicted Total Vocalizations', ylab='Observed Total Vocalizations', main = 'Model Predictability')
abline(a=0, b=1)

plot(predict(logtotal.glm, type='response'), residuals(logtotal.glm, type='response'), xlab='Fitted values', ylab='Residuals', main='Residuals vs Fitted Values')
```

```{r}
#QUESTION ON THESE TYPES OF PLOTS - Since I am including other factors (# of calves, season, and 
# fish call score sums) dooes this matter when making/showing these kinds of plots? 

eq <- function(x,y) {
  m <- lm(y ~ x)
  as.character(
    as.expression(
      substitute(italic(y) == a + b %.% italic(x)*","~~italic(R)^2~"="~R2,
                list(a = format(coef(m)[1], digits = 2),
                b = format(coef(m)[2], digits = 2),
                R2 = format(summary(m)$r.squared, digits = 3)))
    )
  )
}


(prelim_plot <- ggplot(dolphinz, aes(x = dolphin, y = log1p(total))) +
  geom_point() + theme_classic() +
  stat_smooth(method = "lm") + labs(x="Total Dolphins Sighted", y = "Log+1(Total Vocalizations Detected)") + geom_text(x = 25, y = 4.8, label = eq(dolphinz$dolphin,log1p(dolphinz$total)), parse = TRUE))

```

```{r}
#Plots comparing dolphins sightings and vocalization detections across Station and Season by their means + 95% confidence intervals to display significnat differences identified by the model 


#TOTAL VOCALIZATIONS
dolphsite <- ggplot(dolphinz, aes(x=site, y=dolphin)) + 
  geom_jitter(colour="darkslategray4", alpha=0.5, width=0.1) +
  stat_summary(geom = "point", fun = "mean", size = 2) + 
  geom_errorbar(stat="summary", fun.data="mean_se", fun.args = list(mult = 1.96), width=0) +
  labs(x="Survey Area", y="Total Dolphins Sighted mean + 95%CI") +
  theme_bw() + theme_classic() +
  theme(axis.text.x=element_text(angle=45, hjust=1)) 

dolphszn <- ggplot(dolphinz, aes(x=season, y=dolphin)) + 
  geom_jitter(colour="darkslategray4", alpha=0.5, width=0.1) +
  stat_summary(geom = "point", fun = "mean", size = 2) + 
  geom_errorbar(stat="summary", fun.data="mean_se", fun.args = list(mult = 1.96), width=0) +
  labs(x="Season", y="Total Dolphins Sighted mean + 95%CI") +
  theme_bw() + theme_classic() +
  theme(axis.text.x=element_text(angle=45, hjust=1)) 

totsite <- ggplot(dolphinz, aes(x=site, y=log1p(total))) + 
  geom_jitter(colour="gray19", alpha=0.5, width=0.1) +
  stat_summary(geom = "point", fun = "mean", size = 2) + 
  geom_errorbar(stat="summary", fun.data="mean_se", fun.args = list(mult = 1.96), width=0) +
  labs(x="Survey Area", y="Log+1(Total Vocalizations) mean + 95%CI") +
  theme_bw() + theme_classic() +
  theme(axis.text.x=element_text(angle=45, hjust=1)) 

totszn <- ggplot(dolphinz, aes(x=season, y=log1p(total))) + 
  geom_jitter(colour="gray19", alpha=0.5, width=0.1) +
  stat_summary(geom = "point", fun = "mean", size = 2) + 
  geom_errorbar(stat="summary", fun.data="mean_se", fun.args = list(mult = 1.96), width=0) +
  labs(x="Season", y="Log+1(Total Vocalizations) mean + 95%CI") +
  theme_bw() + theme_classic() +
  theme(axis.text.x=element_text(angle=45, hjust=1)) 

#ECHOLOCATION BOUTS
echosite <- ggplot(dolphinz, aes(x=site, y=log1p(echo))) + 
  geom_jitter(colour="blue4", alpha=0.5, width=0.1) +
  stat_summary(geom = "point", fun = "mean", size = 2) + 
  geom_errorbar(stat="summary", fun.data="mean_se", fun.args = list(mult = 1.96), width=0) +
  labs(x="Survey Area", y="Log+1(Total Echo Bouts) mean + 95%CI") +
  theme_bw() + theme_classic() +
  theme(axis.text.x=element_text(angle=45, hjust=1)) 

echoszn <- ggplot(dolphinz, aes(x=season, y=log1p(echo))) + 
  geom_jitter(colour="blue4", alpha=0.5, width=0.1) +
  stat_summary(geom = "point", fun = "mean", size = 2) + 
  geom_errorbar(stat="summary", fun.data="mean_se", fun.args = list(mult = 1.96), width=0) +
  labs(x="Season", y="LLog+1(Total Echo Bouts) mean + 95%CI") +
  theme_bw() + theme_classic() +
  theme(axis.text.x=element_text(angle=45, hjust=1)) 

#BURST PULSES
bpsite <- ggplot(dolphinz, aes(x=site, y=log1p(bp))) + 
  geom_jitter(colour="dark green", alpha=0.5, width=0.1) +
  stat_summary(geom = "point", fun = "mean", size = 2) + 
  geom_errorbar(stat="summary", fun.data="mean_se", fun.args = list(mult = 1.96), width=0) +
  labs(x="Survey Area", y="Log+1(Total Burst Pulses) mean + 95%CI") +
  theme_bw() + theme_classic() +
  theme(axis.text.x=element_text(angle=45, hjust=1)) 

bpszn <- ggplot(dolphinz, aes(x=season, y=log1p(bp))) + 
  geom_jitter(colour="dark green", alpha=0.5, width=0.1) +
  stat_summary(geom = "point", fun = "mean", size = 2) + 
  geom_errorbar(stat="summary", fun.data="mean_se", fun.args = list(mult = 1.96), width=0) +
  labs(x="Season", y="Log+1(Total Burst Pulses) mean + 95%CI") +
  theme_bw() + theme_classic() +
  theme(axis.text.x=element_text(angle=45, hjust=1)) 

#WHISTLES
whistsite <- ggplot(dolphinz, aes(x=site, y=log1p(whist))) + 
  geom_jitter(colour="goldenrod2", alpha=0.5, width=0.1) +
  stat_summary(geom = "point", fun = "mean", size = 2) + 
  geom_errorbar(stat="summary", fun.data="mean_se", fun.args = list(mult = 1.96), width=0) +
  labs(x="Survey Area", y="Log+1(Total Whistles) mean + 95%CI") +
  theme_bw() + theme_classic() +
  theme(axis.text.x=element_text(angle=45, hjust=1)) 


whistszn <- ggplot(dolphinz, aes(x=season, y=log1p(whist))) + 
  geom_jitter(colour="goldenrod2", alpha=0.5, width=0.1) +
  stat_summary(geom = "point", fun = "mean", size = 2) + 
  geom_errorbar(stat="summary", fun.data="mean_se", fun.args = list(mult = 1.96), width=0) +
  labs(x="Season", y="Log+1(Total Whistles) mean + 95%CI") +
  theme_bw() + theme_classic() +
  theme(axis.text.x=element_text(angle=45, hjust=1)) 


grid.arrange(dolphsite, totsite, ncol=2)
grid.arrange(dolphsite, echosite, ncol=2)
grid.arrange(dolphsite, bpsite, ncol=2)
grid.arrange(dolphsite, whistsite, ncol=2)

grid.arrange(dolphszn, totszn, ncol=2)
grid.arrange(dolphszn, echoszn, ncol=2)
grid.arrange(dolphszn, bpszn, ncol=2)
grid.arrange(dolphszn, whistszn, ncol=2)

```

supp figures broken down by site and season to see partitioning of the harbor
```{r}
#Supplemental figures that display seasonal patterns across stations in the same plots to see if this helps us visualize their use of the harbor


dosite <- ggplot(dolphinz, aes(x=site, y=dolphin)) + facet_wrap(~season)+
  geom_jitter(colour="darkslategray4", alpha=0.5, width=0.1) +
  stat_summary(geom = "point", fun = "mean", size = 2) + 
  geom_errorbar(stat="summary", fun.data="mean_se", fun.args = list(mult = 1.96), width=0) +
  labs(x="Survey Area", y="Total Dolphins Sighted mean + 95%CI") +
  theme_bw() + theme_classic() +
  theme(axis.text.x=element_text(angle=45, hjust=1)) 
dosite


totlsite <- ggplot(dolphinz, aes(x=site, y=log1p(total))) + facet_wrap(~season)+
  geom_jitter(colour="gray19", alpha=0.5, width=0.1) +
  stat_summary(geom = "point", fun = "mean", size = 2) + 
  geom_errorbar(stat="summary", fun.data="mean_se", fun.args = list(mult = 1.96), width=0) +
  labs(x="Survey Area", y="Log+1(Total Vocalizations) mean + 95%CI") +
  theme_bw() + theme_classic() +
  theme(axis.text.x=element_text(angle=45, hjust=1)) 
totlsite


echozsite <- ggplot(dolphinz, aes(x=site, y=log1p(echo))) + facet_wrap(~season)+
  geom_jitter(colour="blue4", alpha=0.5, width=0.1) +
  stat_summary(geom = "point", fun = "mean", size = 2) + 
  geom_errorbar(stat="summary", fun.data="mean_se", fun.args = list(mult = 1.96), width=0) +
  labs(x="Survey Area", y="Log+1(Total Echo Bouts) mean + 95%CI") +
  theme_bw() + theme_classic() +
  theme(axis.text.x=element_text(angle=45, hjust=1)) 
echozsite


bpzsite <- ggplot(dolphinz, aes(x=site, y=log1p(bp))) + facet_wrap(~season)+
  geom_jitter(colour="dark green", alpha=0.5, width=0.1) +
  stat_summary(geom = "point", fun = "mean", size = 2) + 
  geom_errorbar(stat="summary", fun.data="mean_se", fun.args = list(mult = 1.96), width=0) +
  labs(x="Survey Area", y="Log+1(Total Burst Pulses) mean + 95%CI") +
  theme_bw() + theme_classic() +
  theme(axis.text.x=element_text(angle=45, hjust=1)) 
bpzsite


whistlsite <- ggplot(dolphinz, aes(x=site, y=log1p(whist))) + facet_wrap(~season)+
  geom_jitter(colour="goldenrod2", alpha=0.5, width=0.1) +
  stat_summary(geom = "point", fun = "mean", size = 2) + 
  geom_errorbar(stat="summary", fun.data="mean_se", fun.args = list(mult = 1.96), width=0) +
  labs(x="Survey Area", y="Log+1(Total Whistles) mean + 95%CI") +
  theme_bw() + theme_classic() +
  theme(axis.text.x=element_text(angle=45, hjust=1)) 
whistlsite

```

ECHO GLM regression
```{r}
elog.glm <- glm(log1p(echo) ~ dolphin + site + season + perch + drum, data = dolphinz)
summary(elog.glm)
plot(elog.glm)
echolog.glm <- aov(elog.glm)
stepAIC(elog.glm)
#drop trout, toad, noiseratio
```

```{r}
#Testing Negative Binomial and Poisson GLM distributions
echo.glmnb <- glm.nb(echo ~ dolphin + site + season + perch, data = dolphinz)
summary(echo.glmnb)
plot(echo.glmnb)
#AIC 607.03

echo.glmpois <- glm(echo ~ dolphin + site + season + perch, family = poisson, data = dolphinz)
summary(echo.glmpois)
plot(echo.glmpois)
#AIC 1646.7

#Gaussian GLM with Log+1 transformation of echolocation bouts best model fit - AIC 338.87
```

```{r}
#Followed up with a likelihood ratio test to compare the effects of each factor - TOTAL VOCALS

elog.glm <- glm(log1p(echo) ~ dolphin + site + season + perch + drum, data = dolphinz)
elog.glm2 <- glm(log1p(echo) ~ site + season + perch + drum, data = dolphinz)
elog.glm3 <- glm(log1p(echo) ~ dolphin + season + perch + drum, data = dolphinz)
elog.glm4 <- glm(log1p(echo) ~ dolphin + site  + perch + drum, data = dolphinz)
elog.glm5 <- glm(log1p(echo) ~ dolphin + site + season + drum, data = dolphinz)
elog.glm6 <- glm(log1p(echo) ~ dolphin + site + season + perch, data = dolphinz)

lrtest(elog.glm, elog.glm2) #dolphin
lrtest(elog.glm, elog.glm3) #site
lrtest(elog.glm, elog.glm4) #season
lrtest(elog.glm, elog.glm5) #perch
lrtest(elog.glm, elog.glm6) #drum
```


```{r}
#Tukeys HSD  multiple comparison of means 
TK.echo <- TK.test(dolphinz$echo, dolphinz$site, a=0.05)
TK.echo

TK.eszn <- TK.test(dolphinz$echo, dolphinz$season, a=0.05)
TK.eszn
```

```{r}
#Pearson Correlations to further assess relationships with continuous variables
#Calf variable (p < 0.001 ) correlations with total dolphins sighted and total vocalizations detected
# echo bouts ~ dolphins sighted
ggscatter(dolphinz, x = "dolphin", y = "echo",
          add = "reg.line",                         
          conf.int = TRUE ,      
 xlab = "Total Dolphins Sighted", ylab = "Log+1(Total Echo Bouts Detected)")+
  stat_cor(aes(x=dolphin, y=log1p(echo)), label.x = 20)

```

```{r}
par(mfrow=c(1,2))

plot(predict(elog.glm), log1p(dolphinz$echo), xlab='Predicted Total Echo Bouts', ylab='Observed Total Echo Bouts', main = 'Model Predictability')
abline(a=0, b=1)

plot(predict(elog.glm, type='response'), residuals(elog.glm, type='response'), xlab='Fitted values', ylab='Residuals', main='Residuals vs Fitted Values')
```
```{r}
Anova(elog.glm)
#remove drum, trout, noiseratio
```

```{r}
stepAIC(elog.glm)
```

```{r}
library(ggplot2)  # load the package

par(mfrow=c(2,2))
(prelim_plot <- ggplot(dolphinz, aes(x = dolphin, y = log1p(echo))) +
  geom_point() + theme_classic() +
  geom_smooth(method = "lm") + labs(x="Total Dolphins Sighted", y = "Log+1(Total Vocalizations Detected)") + geom_text(x = 25, y = 4.8, label = eq(dolphinz$dolphin,log1p(dolphinz$echo)), parse = TRUE))


```


BP - GLM Model
```{r}
bplog.glm <- glm(log1p(bp) ~ dolphin + site + season + drum + toad + trout, data = dolphinz)
summary(bplog.glm)
plot(bplog.glm)
bpalog.glm <- aov(bplog.glm)
summary(bpalog.glm)
stepAIC(bplog.glm)
#remove perch and noise ratio
```

```{r}
#Testing Negative Binomial and Poisson GLM distributions
bp.glmnb <- glm.nb(bp ~ dolphin + site + season + perch + trout + noiseratio, data = dolphinz)
summary(bp.glmnb)
stepAIC(bp.glmnb)
#AIC 239.38

bp.glmpois <- glm(bp ~ dolphin + site + season + perch, family = poisson, data = dolphinz)
summary(bp.glmpois)
plot(bp.glmpois)
#AIC 537.26

#Gaussian GLM with Log+1 transformation of total vocalizations best model fit - AIC 238.38
```


```{r}
#Followed up with a likelihood ratio test to compare the effects of each factor - TOTAL VOCALS

bplog.glm <- glm(log1p(bp) ~ dolphin + site + season + drum + toad + trout, data = dolphinz)
bplog.glm2 <- glm(log1p(bp) ~ site + season + drum + toad + trout, data = dolphinz)
bplog.glm3 <- glm(log1p(bp) ~ dolphin + season + drum + toad + trout, data = dolphinz)
bplog.glm4 <- glm(log1p(bp) ~ dolphin + site + drum + toad + trout, data = dolphinz)
bplog.glm5 <- glm(log1p(bp) ~ dolphin + site + season + toad + trout, data = dolphinz)
bplog.glm6 <- glm(log1p(bp) ~ dolphin + site + season + drum + trout, data = dolphinz)
bplog.glm7 <- glm(log1p(bp) ~ dolphin + site + season + drum + toad, data = dolphinz)

lrtest(bplog.glm, bplog.glm2) #dolphin
lrtest(bplog.glm, bplog.glm3) #site
lrtest(bplog.glm, bplog.glm4) #season
lrtest(bplog.glm, bplog.glm5) #drum
lrtest(bplog.glm, bplog.glm6) #toad
lrtest(bplog.glm, bplog.glm7) #trout
```

```{r}

TK.bp <- TK.test(dolphinz$bp, dolphinz$site, a=0.05)
TK.bp

TK.bpszn <- TK.test(dolphinz$bp, dolphinz$season, a=0.05)
TK.bpszn
```

```{r}
par(mfrow=c(1,2))

plot(predict(bplog.glm), log1p(dolphinz$bp), xlab='Predicted Burst Pulses', ylab='Observed Burst Pulses', main = 'Model Predictability')
abline(a=0, b=1)

plot(predict(bplog.glm, type='response'), residuals(bplog.glm, type='response'), xlab='Fitted values', ylab='Residuals', main='Residuals vs Fitted Values')


par(mfrow=c(1,2))

plot(predict(bp.glmnb), dolphinz$bp, xlab='Predicted Burst Pulses', ylab='Observed Burst Pulses', main = 'Model Predictability')
abline(a=0, b=1)

plot(predict(bp.glmnb, type='response'), residuals(bp.glmnb, type='response'), xlab='Fitted values', ylab='Residuals', main='Residuals vs Fitted Values')

#Further confirmation to use guassian glm with log+1 transformation of burst pulses  instead of negative binomial glm to account for high number of zeros.
```

```{r}
(prelim_plot <- ggplot(dolphinz, aes(x = dolphin, y = log1p(bp))) +
  geom_point() + theme_classic() + labs(x="Total Dolphins Sighted", y = "Log+1(Total Burst Pulses Detected)") + geom_smooth(method = "lm", colour = "dark green") + geom_text(x = 25, y = 4, label = eq(dolphinz$dolphin,log1p(dolphinz$bp)), parse = TRUE))

```

```{r}
#Pearson Correlations to further assess relationships with continuous variables

# total bps ~ dolphins sighted
ggscatter(dolphinz, x = "dolphin", y = "bp",
          add = "reg.line",                         
          conf.int = TRUE ,      
 xlab = "Total Dolphins Sighted", ylab = "Log+1(Total Burst Pulses Detected)")+
  stat_cor(aes(x=dolphin, y=log1p(bp)), label.x = 20)

```

WHISTLE - GLM Regression
```{r}
whlog.glm <- glm(log1p(whist) ~ dolphin + site + season + trout, data = dolphinz)
summary(whlog.glm)
plot(whlog.glm)
stepAIC(whlog.glm)
#drop perch, toad, drum, noise ratio 
whalog.glm <- aov(whlog.glm)
summary(whalog.glm)
```


```{r}
#Testing Negative Binomial and Poisson GLM distributions
wh.glmnb <- glm.nb(whist ~ dolphin + site + season + perch + trout + noiseratio, data = dolphinz)
summary(wh.glmnb)
stepAIC(wh.glmnb)
#AIC 323.68

wh.glmpois <- glm(whist ~ dolphin + site + season + perch, family = poisson, data = dolphinz)
summary(wh.glmpois)
plot(wh.glmpois)
#AIC 570.68

#Gaussian GLM with Log+1 transformation of whistles best model fit - AIC 266.62
```

```{r}
#Followed up with a likelihood ratio test to compare the effects of each factor - WHISTLES

whlog.glm <- glm(log1p(whist) ~ dolphin + site + season + trout, data = dolphinz)
whlog.glm2 <- glm(log1p(whist) ~ site + season + trout, data = dolphinz)
whlog.glm3 <- glm(log1p(whist) ~ dolphin + season + trout, data = dolphinz)
whlog.glm4 <- glm(log1p(whist) ~ dolphin + site + trout, data = dolphinz)
whlog.glm5 <- glm(log1p(whist) ~ dolphin + site + season, data = dolphinz)

lrtest(whlog.glm, whlog.glm2) #dolphin
lrtest(whlog.glm, whlog.glm3) #site
lrtest(whlog.glm, whlog.glm4) #season
lrtest(whlog.glm, whlog.glm5) #trout
```


```{r}
library(DTK)
TK.whistle <- TK.test(dolphinz$whist, dolphinz$site, a=0.05)
TK.whistle

TK.whszn <- TK.test(dolphinz$whist, dolphinz$season, a=0.05)
TK.whszn
```


```{r}
par(mfrow=c(1,2))

plot(predict(whlog.glm), log1p(dolphinz$whist), xlab='Predicted Total Whistles', ylab='Observed Total Whistles', main = 'Model Predictability')
abline(a=0, b=1)

plot(predict(whlog.glm, type='response'), residuals(whlog.glm, type='response'), xlab='Fitted values', ylab='Residuals', main='Residuals vs Fitted Values')
```

```{r}

(prelim_plot <- ggplot(dolphinz, aes(x = dolphin, y = log1p(whist))) +
  geom_point() + theme_classic() + labs(x="Total Dolphins Sighted", y = "Log+1(Total Whistles Detected)") + geom_smooth(method = "lm", colour = "goldenrod2") + geom_text(x = 25, y = 4.2, label =  eq(dolphinz$dolphin,log1p(dolphinz$whist)), parse = TRUE))

```